---
- hosts: localhost
  connection: local
  become: true  
  vars:
    vpn_servers: #au.vpn.private:555
      - ip: 999.999.999.999
        port: 555
        proto: udp
        name: au.vpn.private
      - ip: 888.888.888.888
        port: 666
        proto: udp
        name: au.vpn.private
    vpn_interface: wg0
    allow_imcoming: true
  
  tasks:

  #Vars included from this file will take precedance over what is declared above=12(play vars) include_vars=18
  #https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#understanding-variable-precedence

  - name: Include vars file
    tags: debug
    include_vars:
      file: /home/u/vars.yml

  - name: Display all variables/facts known for a host
    tags: debug
    debug:
      var: vars
  
  - name: disable ipv6
    tags: ipv6
    import_tasks: disableipv6.yml

  - name: Allow VPN IPs 
    tags: firewall
    ufw:
      rule: allow
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
      dest: "{{ item.ip }}"
      direction: out
      comment: "{{ item.name }}"
    loop: "{{ vpn_servers }}"

  #Allow Outbound traffic through VPN Interface
  #sudo ufw allow out on tun0 from any to any
  - name: Allow Outbound traffic through VPN Interface
    ufw:
      rule: allow
      direction: out
      interface: "{{ vpn_interface }}"
      src: any
      dest: any
      comment: Allow Outgoing Traffic Via VPN
  
  #Optional dependant on variable allow_imcoming: yes
  #If set to no this rule will not be enabled
  #Allow Incoming traffic through VPN Interface
  #sudo ufw allow out on tun0 from any to any
  - name: Allow Incoming traffic through VPN Interface
    ufw:
      rule: allow
      direction: in
      interface: "{{ vpn_interface }}"
      src: any
      dest: any
      comment: Allow Incoming Traffic Via VPN
    when: 
      - "{{ allow_incoming | bool }} == true"
